# Action name
name: Action

on:
    push

jobs:
    test-job:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/mengrand/my-ubuntu:latest
            credentials:
               username: mengrand
               password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
        steps:
            - name: step
              shell: bash
              run: |
                echo "-- Test IT --"
            - name: checkout project
              uses: actions/checkout@v4
            - name: step
              shell: bash
              run: |
                echo `pwd`            
