name: delivery automation production build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: mylocalrunner
    steps:
      - name: upload deliveries
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: C:\temp\e964dd50a704970b84ebe340115900e385f510fe\*.pck
  build pages:
    uses: ./.github/workflows/static.yml
    with:
      build_workflow_run_id: ${{ github.run_id }}
