# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  workflow_run:
    workflows: [ 'delivery automation production build' ]
    types: [ completed ]
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
          - name: download package artifact
            uses: actions/download-artifact@v4
            with:
              run-id: ${{ github.event.workflow_run.id }}
              github-token: ${{ github.token }}
              name: deliveries
          - name: build docs
            shell: bash
            run: |
                ls -R
                pwd
